import { Avatar } from '../types';

export const AVAILABLE_AVATARS: Avatar[] = [
    // ── STARTER ──────────────────────────────────
    {
        id: 'default',
        name: 'Novice',
        cost: 0,
        icon: 'User',
        color: 'text-gray-400',
        rarity: 'STARTER',
        category: 'warriors',
    },

    // ── COMMON (Warriors & Animals) ──────────────
    {
        id: 'sword',
        name: 'Warrior Blade',
        cost: 50,
        icon: 'Sword',
        color: 'text-amber-500',
        rarity: 'COMMON',
        category: 'warriors',
    },
    {
        id: 'shield',
        name: 'Guardian Shield',
        cost: 75,
        icon: 'Shield',
        color: 'text-blue-400',
        rarity: 'COMMON',
        category: 'warriors',
    },
    {
        id: 'cat',
        name: 'Shadow Cat',
        cost: 60,
        icon: 'Cat',
        color: 'text-orange-400',
        rarity: 'COMMON',
        category: 'animals',
    },
    {
        id: 'dog',
        name: 'Loyal Hound',
        cost: 60,
        icon: 'Dog',
        color: 'text-amber-600',
        rarity: 'COMMON',
        category: 'animals',
    },
    {
        id: 'bird',
        name: 'Sky Hawk',
        cost: 80,
        icon: 'Bird',
        color: 'text-sky-400',
        rarity: 'COMMON',
        category: 'animals',
    },
    {
        id: 'heart',
        name: 'Pure Heart',
        cost: 90,
        icon: 'Heart',
        color: 'text-pink-400',
        rarity: 'COMMON',
        category: 'mystic',
    },

    // ── RARE ──────────────────────────────────────
    {
        id: 'flame',
        name: 'Eternal Flame',
        cost: 150,
        icon: 'Flame',
        color: 'text-orange-500',
        rarity: 'RARE',
        category: 'warriors',
    },
    {
        id: 'zap',
        name: 'Thunder Strike',
        cost: 200,
        icon: 'Zap',
        color: 'text-yellow-400',
        rarity: 'RARE',
        category: 'warriors',
    },
    {
        id: 'moon',
        name: 'Lunar Guardian',
        cost: 180,
        icon: 'Moon',
        color: 'text-indigo-400',
        rarity: 'RARE',
        category: 'cosmic',
    },
    {
        id: 'sun',
        name: 'Solar Flare',
        cost: 200,
        icon: 'Sun',
        color: 'text-amber-400',
        rarity: 'RARE',
        category: 'cosmic',
    },
    {
        id: 'tree',
        name: 'Ancient Grove',
        cost: 170,
        icon: 'TreePine',
        color: 'text-emerald-500',
        rarity: 'RARE',
        category: 'mystic',
    },
    {
        id: 'mountain',
        name: 'Stone Titan',
        cost: 220,
        icon: 'Mountain',
        color: 'text-slate-400',
        rarity: 'RARE',
        category: 'warriors',
    },
    {
        id: 'snowflake',
        name: 'Frost Whisper',
        cost: 250,
        icon: 'Snowflake',
        color: 'text-cyan-300',
        rarity: 'RARE',
        category: 'mystic',
    },

    // ── EPIC ──────────────────────────────────────
    {
        id: 'ghost',
        name: 'Phantom Apparition',
        cost: 400,
        icon: 'Ghost',
        color: 'text-purple-400',
        rarity: 'EPIC',
        category: 'mystic',
    },
    {
        id: 'rocket',
        name: 'Star Voyager',
        cost: 500,
        icon: 'Rocket',
        color: 'text-red-400',
        rarity: 'EPIC',
        category: 'cosmic',
        isNew: true,
    },
    {
        id: 'orbit',
        name: 'Cosmic Orbit',
        cost: 550,
        icon: 'Orbit',
        color: 'text-violet-400',
        rarity: 'EPIC',
        category: 'cosmic',
        isNew: true,
    },
    {
        id: 'diamond',
        name: 'Diamond Edge',
        cost: 600,
        icon: 'Diamond',
        color: 'text-cyan-400',
        rarity: 'EPIC',
        category: 'royalty',
    },
    {
        id: 'wand',
        name: 'Arcane Wand',
        cost: 650,
        icon: 'Wand2',
        color: 'text-fuchsia-400',
        rarity: 'EPIC',
        category: 'mystic',
        isNew: true,
    },
    {
        id: 'bot',
        name: 'Mecha Prime',
        cost: 700,
        icon: 'Bot',
        color: 'text-teal-400',
        rarity: 'EPIC',
        category: 'cosmic',
    },
    {
        id: 'star',
        name: 'Celestial Star',
        cost: 750,
        icon: 'Star',
        color: 'text-yellow-300',
        rarity: 'EPIC',
        category: 'cosmic',
    },

    // ── LEGENDARY ────────────────────────────────
    {
        id: 'crown',
        name: 'Royal Crown',
        cost: 1500,
        icon: 'Crown',
        color: 'text-yellow-500',
        rarity: 'LEGENDARY',
        category: 'royalty',
    },
    {
        id: 'gem',
        name: 'Infinity Gem',
        cost: 2000,
        icon: 'Gem',
        color: 'text-emerald-400',
        rarity: 'LEGENDARY',
        category: 'royalty',
        isNew: true,
    },
    {
        id: 'skull',
        name: 'Abyssal Skull',
        cost: 2500,
        icon: 'Skull',
        color: 'text-red-500',
        rarity: 'LEGENDARY',
        category: 'warriors',
    },
    {
        id: 'sparkles',
        name: 'Divine Sparkle',
        cost: 3000,
        icon: 'Sparkles',
        color: 'text-amber-300',
        rarity: 'LEGENDARY',
        category: 'mystic',
    },
    {
        id: 'cloud',
        name: 'Nimbus Lord',
        cost: 5000,
        icon: 'Cloud',
        color: 'text-sky-300',
        rarity: 'LEGENDARY',
        category: 'cosmic',
    },

    // ── MYTHIC (Ultimate Legendary — beyond reach) ─────
    {
        id: 'trophy_apex',
        name: 'Apex Trophy',
        cost: 7500,
        icon: 'Trophy',
        color: 'text-amber-300',
        rarity: 'MYTHIC',
        category: 'royalty',
        isNew: true,
    },
    {
        id: 'atom_sovereign',
        name: 'Atomic Sovereign',
        cost: 9000,
        icon: 'Atom',
        color: 'text-cyan-300',
        rarity: 'MYTHIC',
        category: 'cosmic',
        isNew: true,
    },
    {
        id: 'mindforge',
        name: 'Mindforge',
        cost: 11000,
        icon: 'Brain',
        color: 'text-fuchsia-300',
        rarity: 'MYTHIC',
        category: 'mystic',
        isNew: true,
    },
    {
        id: 'crosshair_apex',
        name: 'Apex Predator',
        cost: 13000,
        icon: 'Crosshair',
        color: 'text-rose-400',
        rarity: 'MYTHIC',
        category: 'warriors',
        isNew: true,
    },
    {
        id: 'world_architect',
        name: 'World Architect',
        cost: 15000,
        icon: 'Globe2',
        color: 'text-emerald-300',
        rarity: 'MYTHIC',
        category: 'mystic',
        isNew: true,
    },
    {
        id: 'eternal_loop',
        name: 'Eternal Loop',
        cost: 18000,
        icon: 'Infinity',
        color: 'text-violet-300',
        rarity: 'MYTHIC',
        category: 'cosmic',
        isNew: true,
    },
    {
        id: 'genesis_strand',
        name: 'Genesis Strand',
        cost: 25000,
        icon: 'Dna',
        color: 'text-teal-300',
        rarity: 'MYTHIC',
        category: 'mystic',
        isNew: true,
    },
];

export const AVATAR_CATEGORIES = [
    { id: 'all' as const, label: 'All', emoji: '🏪' },
    { id: 'warriors' as const, label: 'Warriors', emoji: '⚔️' },
    { id: 'cosmic' as const, label: 'Cosmic', emoji: '🌌' },
    { id: 'animals' as const, label: 'Animals', emoji: '🐾' },
    { id: 'royalty' as const, label: 'Royalty', emoji: '👑' },
    { id: 'mystic' as const, label: 'Mystic', emoji: '🔮' },
] as const;

export type CategoryFilter = typeof AVATAR_CATEGORIES[number]['id'];
